const scenariors =  {
  "Home": {
    "Bedroom": ["Morning routine after waking up", "Getting ready for the day", "Relaxing before bed", "Searching for a lost item", "Tidying the nightstand", "Changing bedsheets", "Choosing an outfit", "Checking the alarm clock", "Packing a bag for work or school", "Listening to music while lying down"],
    "Master Bedroom": ["Organizing clothes and accessories", "Making the bed", "Getting dressed for work", "Relaxing with a book", "Checking phone notifications", "Planning the day", "Adjusting curtains or blinds"],
    "Guest Bedroom": ["Preparing the room for visitors", "Tidying after guests leave", "Changing bed linens", "Adding fresh towels or pillows"],
    "Kids' Room": ["Cleaning toys and books", "Organizing school supplies", "Playing with children", "Helping kids get dressed", "Reading a bedtime story"],
    "Bathroom": ["Morning hygiene routine", "Showering", "Brushing teeth", "Cleaning the bathroom", "Washing hands after coming home", "Applying skincare", "Checking hair in the mirror"],
    "Master Bathroom": ["Doing skincare routine", "Shaving or grooming", "Preparing for a night out", "Relaxing in the bathtub"],
    "Kitchen": ["Making breakfast", "Preparing lunch or dinner", "Cleaning dishes", "Meal prepping", "Washing fruits and vegetables", "Organizing cabinets", "Checking expiration dates", "Baking a dessert"],
    "Dining Room": ["Eating a meal with family", "Setting the table", "Cleaning after eating", "Having a casual snack", "Hosting a small gathering"],
    "Living Room": ["Watching TV", "Relaxing on the couch", "Hosting a guest", "Doing a hobby", "Playing video games", "Reading a book", "Listening to music"],
    "Laundry Room": ["Doing laundry", "Folding clothes", "Ironing clothes", "Sorting dirty laundry", "Checking laundry detergent"],
    "Balcony": ["Watering plants", "Enjoying morning coffee", "Relaxing outdoors", "Hanging laundry to dry", "Watching the street below"],
    "Patio": ["Barbecuing", "Relaxing with friends", "Tidying outdoor furniture", "Decorating with lights", "Enjoying fresh air in the evening"],
    "Entryway / Hallway": ["Putting on shoes before leaving", "Coming back home", "Organizing coats and bags", "Wiping feet on a mat", "Greeting visitors"],
    "Storage Room": ["Looking for stored items", "Organizing boxes", "Cleaning the storage space", "Checking old belongings", "Preparing items for donation"],
    "Home Office": ["Starting a work session", "Organizing the desk", "Preparing for a meeting", "Taking a coffee break", "Answering emails", "Sorting documents"],
    "Garage": ["Parking the car", "Cleaning the garage", "Working on a project", "Checking tools", "Storing sports equipment"],
    "Basement": ["Organizing stored items", "Doing a DIY project", "Cleaning the basement", "Working on hobbies", "Checking the water heater or pipes"],
    "Attic": ["Searching for old items", "Organizing boxes", "Cleaning dust and cobwebs", "Checking holiday decorations"],
    "Walk-in Closet": ["Choosing an outfit", "Organizing clothes", "Cleaning shelves", "Trying on shoes", "Checking for seasonal items"],
    "Pantry": ["Restocking ingredients", "Cleaning shelves", "Looking for snacks", "Checking expiration dates", "Organizing cans and jars"]
  },
  "BuildingsAndFacilities": {
    "Apartment Lobby": ["Picking up mail", "Passing through on the way out", "Meeting someone", "Waiting for an elevator", "Talking to a neighbor", "Checking notices on a bulletin board"],
    "Elevator": ["Riding alone", "Riding with neighbors", "Carrying groceries", "Pressing the wrong floor by accident", "Checking phone while waiting"],
    "Stairwell": ["Walking up the stairs", "Walking down the stairs", "Exercising on stairs", "Talking quietly to someone", "Carrying items upstairs"],
    "Rooftop": ["Enjoying the view", "Watering rooftop plants", "Relaxing outdoors", "Taking photos", "Exercising or stretching"],
    "Underground Parking": ["Parking the car", "Walking to the elevator", "Finding a parking space", "Checking car for damage", "Carrying items to the car"],
    "Gym": ["Starting a workout", "Using machines", "Cooling down", "Stretching before exercise", "Talking to a trainer"],
    "Swimming Pool": ["Doing laps", "Relaxing by the pool", "Preparing to swim", "Teaching someone to swim", "Checking pool rules"],
    "Mailroom": ["Picking up packages", "Sorting mail", "Checking notices", "Reporting a missing package"],
    "Reception Desk": ["Asking for information", "Checking in", "Waiting for service", "Giving a package to a visitor"],
    "Security Office": ["Monitoring cameras", "Checking visitor logs", "Reporting an issue", "Patrolling the building"],
    "Conference Hall": ["Attending a meeting", "Setting up an event", "Cleaning after a meeting", "Testing the projector or sound system"],
    "Public Lounge": ["Relaxing", "Meeting someone", "Reading or working", "Waiting for an appointment"],
    "Vending Machine Area": ["Buying a snack", "Choosing a drink", "Waiting for change", "Restocking machines"]
  },
  "StoresAndMarkets": {
    "Grocery Store / Supermarket": ["Shopping for groceries", "Comparing prices", "Buying fresh produce", "Looking for sales", "Checking expiration dates", "Using a shopping cart or basket"],
    "Convenience Store": ["Buying a quick snack", "Getting a drink", "Paying at the counter", "Looking for small household items", "Checking store promotions"],
    "Clothing Store": ["Browsing clothes", "Trying on outfits", "Comparing accessories", "Asking about sizes", "Checking sales tags"],
    "Electronics Store": ["Looking at gadgets", "Comparing devices", "Asking for advice", "Testing headphones or speakers", "Checking product specs"],
    "Pharmacy": ["Picking up medicine", "Buying health products", "Consulting the pharmacist", "Checking prices of over-the-counter items", "Looking for supplements"],
    "Bookstore": ["Browsing books", "Reading sample chapters", "Buying a novel", "Checking for new releases", "Asking for recommendations"],
    "Furniture Store": ["Checking furniture displays", "Sitting on chairs", "Comparing prices", "Testing mattresses or sofas", "Looking for home decor items"],
    "Bakery": ["Choosing baked goods", "Buying bread", "Waiting in line", "Sampling pastries", "Asking about ingredients"],
    "Café": ["Ordering a drink", "Sitting and relaxing", "Working on a laptop", "Meeting a friend", "Trying seasonal drinks"],
    "Farmers Market": ["Buying fresh produce", "Comparing fruits", "Talking to vendors", "Checking for organic options", "Sampling products"],
    "Pet Store": ["Looking at pets", "Buying pet supplies", "Asking for advice", "Checking new arrivals"],
    "Toy Store": ["Browsing toys", "Buying gifts", "Checking new arrivals", "Testing toys in-store"],
    "Hardware Store": ["Buying tools", "Comparing materials", "Asking staff for help", "Picking paint or hardware"],
    "Beauty Supply Store": ["Choosing makeup products", "Comparing skincare items", "Asking for recommendations", "Testing new products"],
    "Sports Store": ["Looking for sports gear", "Trying on equipment", "Comparing brands", "Checking sizes"],
    "Jewelry Store": ["Browsing necklaces and rings", "Asking about prices", "Buying gifts", "Checking for sales"],
    "Thrift Shop": ["Browsing used items", "Finding unique pieces", "Trying clothes on", "Checking labels for quality"],
    "Department Store": ["Walking through aisles", "Shopping for multiple items", "Comparing brands", "Checking store sections"],
    "Music Store": ["Looking at instruments", "Testing equipment", "Buying music accessories", "Asking for advice on gear"]
  },
  "FoodAndDining": {
    "Restaurant": ["Ordering food from the menu", "Waiting for the waiter", "Eating with friends or family", "Celebrating a special occasion", "Checking the bill"],
    "Fast Food Place": ["Ordering at the counter", "Eating quickly", "Picking up a takeaway", "Trying a new menu item", "Watching the kitchen preparation"],
    "Food Court": ["Choosing which stall to eat from", "Sharing a table with strangers", "Waiting in line", "Eating with coworkers or friends", "Cleaning up after eating"],
    "Coffee Shop": ["Ordering a specialty coffee", "Sitting and reading", "Working on a laptop", "Meeting a friend", "Trying a seasonal drink"],
    "Ice Cream Shop": ["Choosing a flavor", "Trying a sample", "Eating ice cream outside", "Buying a cone for a child", "Watching others eat their treats"],
    "Buffet": ["Choosing multiple dishes", "Going back for seconds", "Comparing foods with friends", "Trying new cuisines", "Cleaning up plates after eating"],
    "Bar": ["Ordering a drink", "Chatting with friends", "Watching sports on TV", "Listening to music or a live band", "Waiting for a bartender to serve"],
    "Dessert Shop": ["Choosing cakes or pastries", "Sampling desserts", "Buying a special treat", "Asking about ingredients", "Watching the preparation"],
    "Tea House": ["Ordering tea", "Relaxing with friends", "Tasting different teas", "Enjoying snacks with tea", "Reading a book"],
    "Street Food Stall": ["Choosing food from the menu", "Watching the cooking process", "Eating outside", "Talking to the vendor", "Waiting for the food to be ready"],
    "BBQ Restaurant": ["Grilling meat at the table", "Choosing sauces and sides", "Eating with friends or family", "Talking while cooking", "Trying a new recipe"]
  },
  "PublicPlaces": {
    "Park": ["Walking or jogging", "Playing sports", "Picnicking", "Watching birds or nature", "Relaxing on a bench"],
    "Playground": ["Playing on swings", "Watching children play", "Trying the slide or climbing structures", "Meeting other parents", "Pushing a child on a swing"],
    "Street": ["Walking along the sidewalk", "Watching traffic", "Window shopping", "Waiting to cross the street", "Bumping into a friend"],
    "Sidewalk": ["Walking with a friend", "Jogging", "Talking on the phone", "Observing street vendors", "Pushing a stroller"],
    "Bus Stop": ["Waiting for the bus", "Checking the schedule", "Talking to fellow commuters", "Reading a book", "Listening to music"],
    "Train Station": ["Buying tickets", "Waiting on the platform", "Watching trains arrive and depart", "Asking for directions", "Carrying luggage"],
    "Airport": ["Checking in for a flight", "Waiting at the gate", "Going through security", "Eating at a restaurant", "Watching planes take off"],
    "Library": ["Reading a book", "Searching for a specific title", "Studying quietly", "Checking out books", "Using a computer"],
    "Museum": ["Looking at exhibits", "Taking photos", "Reading information plaques", "Attending a guided tour", "Watching a demonstration"],
    "Theater": ["Watching a play", "Waiting for the show to start", "Reading the program", "Buying snacks or drinks", "Talking during intermission"],
    "Cinema": ["Buying tickets", "Watching a movie", "Eating popcorn", "Finding seats", "Checking showtimes"],
    "Mall": ["Shopping for clothes or accessories", "Eating at the food court", "Browsing stores", "Window shopping", "Attending an event or promotion"],
    "Public Restroom": ["Washing hands", "Checking appearance in the mirror", "Cleaning up after use", "Waiting for a stall", "Restocking soap or paper towels"],
    "Community Center": ["Attending a class or workshop", "Meeting neighbors", "Using facilities for recreation", "Organizing events", "Chatting with staff"],
    "Sports Stadium": ["Watching a game", "Buying snacks", "Taking photos", "Meeting friends", "Finding seats"],
    "Swimming Pool (Public)": ["Swimming laps", "Relaxing on a lounge chair", "Watching children play", "Diving or practicing skills", "Changing in locker rooms"],
    "Skate Park": ["Skateboarding", "Watching others perform tricks", "Practicing tricks", "Socializing with friends", "Taking a break on the benches"],
    "Fountain Plaza": ["Walking through", "Taking photos", "Sitting near the fountain", "Listening to music or street performers", "Meeting someone"],
    "City Square": ["Attending a festival or market", "Watching performances", "Relaxing on benches", "Taking photos", "Talking with friends"]
  },
  "SchoolAcademic": {
    "Classroom": ["Attending a lecture", "Writing notes", "Asking questions", "Listening to the teacher", "Working on a group project"],
    "Hallway": ["Walking to the next class", "Talking with friends", "Checking lockers", "Waiting for the bell", "Observing posters on the walls"],
    "Cafeteria": ["Buying lunch", "Eating with friends", "Cleaning the table after eating", "Checking the menu", "Waiting in line"],
    "Dorm Room": ["Studying", "Tidying up", "Chatting with roommates", "Decorating walls", "Listening to music"],
    "Study Room": ["Working on assignments", "Using the library computer", "Studying quietly", "Meeting for a group study session", "Reading textbooks"],
    "Library (school)": ["Checking out books", "Studying", "Researching topics", "Using online resources", "Reading quietly"],
    "Lab": ["Conducting experiments", "Taking notes", "Wearing safety equipment", "Cleaning equipment", "Observing results"],
    "Gymnasium": ["Playing basketball or volleyball", "Exercising", "Stretching before activities", "Watching a game", "Joining a class"],
    "Locker Room": ["Changing clothes", "Hanging towels", "Talking with teammates", "Checking shoes and equipment", "Cleaning lockers"],
    "Auditorium": ["Watching a presentation", "Listening to a lecture", "Waiting for a show to start", "Applauding performers", "Taking photos"],
    "School Bus": ["Riding to school", "Chatting with classmates", "Looking out the window", "Finding a seat", "Listening to music"],
    "Teacher’s Office": ["Asking questions", "Submitting assignments", "Discussing grades", "Collecting materials", "Scheduling meetings"],
    "Counseling Office": ["Talking about problems", "Getting advice", "Filling out forms", "Listening to guidance", "Waiting for a session"],
    "Computer Lab": ["Working on assignments", "Using software", "Printing documents", "Researching online", "Collaborating with classmates"]
  },
  "WorkOffices": {
    "Office Desk": ["Starting the workday", "Organizing papers", "Answering emails", "Making phone calls", "Using the computer for tasks"],
    "Break Room": ["Making coffee", "Eating lunch", "Chatting with coworkers", "Cleaning the table", "Restocking supplies"],
    "Meeting Room": ["Attending a meeting", "Giving a presentation", "Taking notes", "Discussing a project", "Setting up the projector"],
    "Elevator Lobby": ["Waiting for the elevator", "Talking with colleagues", "Checking messages on phone", "Watching others arrive", "Holding the door for someone"],
    "Reception Area": ["Greeting visitors", "Answering the phone", "Checking in guests", "Organizing forms", "Directing visitors"],
    "Coworking Space": ["Working at a shared desk", "Networking with others", "Using communal printers", "Taking a short break", "Attending a workshop"],
    "Pantry": ["Making tea or coffee", "Grabbing a snack", "Restocking items", "Cleaning counters", "Chatting with coworkers"],
    "Printing Room": ["Printing documents", "Collecting copies", "Fixing a paper jam", "Organizing printed materials", "Using the scanner"],
    "Warehouse": ["Organizing inventory", "Checking stock levels", "Loading boxes", "Using equipment like forklifts", "Packing shipments"],
    "Server Room": ["Monitoring servers", "Checking cables", "Adjusting temperature controls", "Performing maintenance", "Running diagnostics"]
  },
  "Transportation": {
    "Car": ["Driving to work or school", "Listening to music or podcast", "Stopping at a traffic light", "Parking", "Checking mirrors and signals"],
    "Bus": ["Waiting at a bus stop", "Finding a seat", "Paying the fare", "Observing fellow passengers", "Reading or listening to music"],
    "Train": ["Waiting on the platform", "Checking the schedule", "Finding a seat", "Watching scenery pass by", "Reading during the ride"],
    "Subway": ["Entering the station", "Using a ticket or pass", "Waiting for the train", "Holding onto a pole", "Checking stops"],
    "Taxi / Ride-share": ["Ordering a ride", "Talking with the driver", "Following the route on GPS", "Paying at the end of the ride", "Giving feedback"],
    "Bicycle / Bike Lane": ["Riding to work or school", "Using a helmet and safety gear", "Following traffic rules", "Stopping at a crosswalk", "Parking the bike"],
    "Airport Gate": ["Waiting for boarding", "Checking the flight information", "Buying a snack", "Watching the plane arrive", "Reading a book or phone"],
    "Airplane": ["Finding your seat", "Storing luggage in the overhead compartment", "Reading or watching movies", "Listening to announcements", "Talking quietly to neighbors"],
    "Train Platform": ["Waiting for the train", "Checking the arrival board", "Observing incoming trains", "Moving luggage", "Buying tickets from a kiosk"],
    "Ticket Counter": ["Buying tickets", "Asking about schedules", "Paying for a ticket", "Receiving a receipt", "Asking about discounts"],
    "Ferry": ["Buying a ticket", "Watching the water", "Taking photos", "Sitting on deck", "Observing other passengers"],
    "Ship Deck": ["Enjoying the view", "Feeling the wind", "Taking photos", "Relaxing on a chair", "Walking along the deck"],
    "Gas Station": ["Filling gas", "Paying inside", "Checking tire pressure", "Cleaning windshield", "Buying snacks or drinks"],
    "Parking Lot": ["Finding a parking spot", "Walking to the entrance", "Checking your car", "Exiting carefully", "Watching other vehicles"],
    "Toll Booth": ["Paying the toll", "Waiting in line", "Checking the receipt", "Talking to staff", "Moving on after payment"]
  },
  "OutdoorsNature": {
    "Beach": ["Walking along the shore", "Swimming in the water", "Sunbathing", "Collecting shells", "Playing beach games"],
    "Forest": ["Hiking on trails", "Observing wildlife", "Taking photos of nature", "Listening to birds", "Collecting leaves or rocks"],
    "Mountain Trail": ["Hiking uphill", "Taking a break at a viewpoint", "Using trekking poles", "Observing scenery", "Checking maps or GPS"],
    "Riverbank": ["Fishing", "Skipping stones", "Picnicking", "Watching ducks or birds", "Walking along the water"],
    "Garden": ["Watering plants", "Pruning flowers", "Checking soil", "Planting new seeds", "Harvesting vegetables"],
    "Backyard": ["Mowing the lawn", "Playing with pets", "Setting up chairs", "Gardening", "Hosting a barbecue"],
    "Lakeside": ["Fishing", "Boating", "Relaxing on the shore", "Taking photos", "Walking along trails"],
    "Meadow": ["Walking through flowers", "Having a picnic", "Observing insects", "Taking photos", "Lying down and relaxing"],
    "Campsite": ["Setting up a tent", "Starting a campfire", "Cooking outdoors", "Watching the stars", "Collecting firewood"],
    "Desert": ["Hiking dunes", "Watching the sunset", "Taking photos of landscape", "Checking navigation", "Observing desert wildlife"],
    "Cliffside": ["Observing the view", "Taking photos", "Hiking carefully along trails", "Resting on rocks", "Using binoculars"],
    "Waterfall": ["Observing the waterfall", "Taking photos", "Walking on nearby trails", "Listening to the water", "Picnicking nearby"],
    "Hiking Hut": ["Resting after a hike", "Checking trail maps", "Preparing a snack", "Talking with other hikers", "Observing the surroundings"],
    "Botanical Garden": ["Walking through flower paths", "Taking photos", "Learning plant names", "Sitting on benches", "Observing butterflies or birds"]
  },
  "Services": {
    "Hospital": ["Checking in at reception", "Waiting to see a doctor", "Observing patients", "Filling out forms", "Talking to nurses"],
    "Clinic": ["Booking an appointment", "Waiting in the lobby", "Getting a check-up", "Talking to the receptionist", "Collecting prescription"],
    "Post Office": ["Mailing a letter or package", "Waiting in line", "Buying stamps", "Asking about delivery times", "Collecting a parcel"],
    "Bank": ["Depositing or withdrawing money", "Talking to a teller", "Waiting in line", "Checking account information", "Using the ATM"],
    "Salon / Barbershop": ["Getting a haircut", "Washing hair", "Choosing a hairstyle", "Chatting with the stylist", "Waiting for service"],
    "Repair Shop": ["Dropping off a device or appliance", "Explaining the issue", "Waiting for service", "Picking up repaired items", "Paying for the repair"],
    "Dentist": ["Getting a dental check-up", "Brushing and flossing advice", "Waiting for the dentist", "Cleaning teeth", "Discussing treatment options"],
    "Optician": ["Getting eyes checked", "Trying on glasses", "Choosing lenses", "Paying for glasses", "Asking about prescriptions"],
    "Police Station": ["Reporting an incident", "Asking for information", "Filing a report", "Waiting in the lobby", "Talking to an officer"],
    "Fire Station": ["Observing fire trucks", "Talking to firefighters", "Participating in a safety demonstration", "Checking fire equipment", "Learning about safety protocols"],
    "Government Office": ["Filling out forms", "Waiting in line", "Submitting documents", "Talking to staff", "Collecting official papers"],
    "Embassy": ["Applying for a visa", "Submitting documents", "Waiting for an appointment", "Asking questions about procedures", "Collecting paperwork"],
    "Laundry Shop": ["Dropping off clothes", "Waiting for service", "Picking up cleaned clothes", "Paying for laundry", "Checking laundry tags"],
    "Dry Cleaner": ["Dropping off delicate clothing", "Waiting for service", "Picking up cleaned items", "Paying for service", "Checking for stains"],
    "Printing Shop": ["Printing documents", "Making copies", "Scanning files", "Collecting printed materials", "Asking for design advice"]
  }
}

export default scenariors;